"""
Globals for layouts
"""
from numpy import sqrt

GOLDEN_RATIO = (1 + sqrt(5))/2.

WIDTH_A4 = 5.78851 # inch
FIGSIZE_A4_LANDSCAPE = (WIDTH_A4, WIDTH_A4/GOLDEN_RATIO)
FIGSIZE_A4 = (WIDTH_A4, (WIDTH_A4/GOLDEN_RATIO) + WIDTH_A4)
FIGSIZE_A4_SQUARE = (WIDTH_A4, WIDTH_A4)



