# some 'reasonable' defaults
# Default plot styles (color, linewidth, etc
# for a couple of cases
# use single quotes ('') for latex so it won't escape

canvas: {
        leftpadding: 0.15,
        rightpadding: 0.05,
        toppadding:  0.0,
        bottompadding: 0.1,
        }

savefig: {
        dpi: 350,
        facecolor: 'w',
        edgecolor: 'w',
        transparent: False,
        bbox_inches: 'tight'       
}

legend: {
        bbox_to_anchor: [0., 1.0, 1., .102],
        loc: 3,
        frameon: True,
        ncol: 3,
        framealpha: 1.,
        borderaxespad: 0,
        mode: "expand",
        handlelength: 2,
        numpoints: 1
}

legendwidth: 1.5

categories: [{name: 'data',
     label: 'exp',
     histscatter: 'scatter',
     dashistyle:{
         color: 'k',
         linewidth: 3,
         alpha: 1.,
         filled: False
         },
    dashistylescatter: {
         color: 'k',
         linewidth: 3,
         alpha: 1.,
         marker: 'o',
         markersize: 4
         }
    },
    {name: 'exp',
     label: 'exp',
     histscatter: 'scatter',
     dashistyle:{
         color: 'k',
         linewidth: 3,
         alpha: 1.,
         filled: False
         },
    dashistylescatter: {
         color: 'k',
         linewidth: 3,
         alpha: 1.,
         marker: 'o',
         markersize: 4
         }
    },
    {name: 'atmos_mu',
    label: '$\mu_{atm}$',
    dashistyle:{
         color: 0,
         linewidth: 3,
         alpha: .6,
         filled: True,
         hatch: False
         },
    dashistylescatter:{
        marker: 'None',
        color: 0
        },
    histscatter: 'overlay'
    },
    {name: 'mu',
    label: '$\mu_{atm}$',
    dashistyle:{
         color: 3,
         linewidth: 3,
         alpha: .6,
         filled: True,
         hatch: False
         },
    dashistylescatter:{
        marker: 'None',
        color: 0
        },
    histscatter: 'overlay'
    },
    {name: 'corsika',
    label: '$\mu_{atm}$',
    dashistyle:{
         color: 0,
         linewidth: 3,
         alpha: .6,
         filled: True,
         hatch: False         
         },
    dashistylescatter:{
        marker: 'None',
        color: 0
        },
    histscatter: 'overlay'
    },
    {name: 'atmos_cc_mu',
    label: 'cc $\mu_{atm}$',
    dashistyle:{
         color: 5,
         linewidth: 3,
         alpha: .8,
         filled: True,
         linestyle: 'solid',
         hatch: '//'         
         },
    histscatter: 'line'
    },
    {name: 'astro_nu',
    label: '$\nu_{astr}$',
    dashistyle:{
         color: 2,
         linewidth: 3,
         alpha: 1.,
         filled: False,
         linestyle: 'solid',
         },
    histscatter: 'line'
    },
    {name: 'conv_nu',
    label: 'HKKMS06',
    dashistyle:{
         color: 1,
         linewidth: 3,
         alpha: 1.,
         filled: False,
         linestyle: 'solid',
         },
    histscatter: 'line'
    },
    {name: 'prompt_nu',
    label: 'ERS',
    dashistyle:{
         color: 3,
         linewidth: 3,
         alpha: 1.,
         filled: False,
         linestyle: 'solid',
         },
    histscatter: 'line'
    },
    {name: 'astro_nue',
    label: '$\nu_{e_{astr}}$',
    dashistyle:{
         color: 2,
         linewidth: 3,
         alpha: 1.,
         filled: False,
         linestyle: 'solid',
         },
    histscatter: 'line'
    },
    {name: 'astro_numu',
    label: '$\nu_{\mu_{astr}}$',
    dashistyle:{
         color: 0,
         linewidth: 3,
         alpha: 1.,
         filled: False,
         linestyle: 'solid',
         },
    histscatter: 'line'
    },
    {name: 'astro_nutau',
    label: '$\nu_{\tau_{astr}}$',
    dashistyle:{
         color: 2,
         linewidth: 3,
         alpha: 1.,
         filled: False,
         linestyle: 'solid',
         },
    histscatter: 'line'
    },
    {name: 'conv_nue',
    label: 'HKKMS06 $\nu_e$',
    dashistyle:{
         color: 1,
         linewidth: 3,
         alpha: 1.,
         filled: False,
         linestyle: 'solid',
         },
    histscatter: 'line'
    },
    {name: 'conv_numu',
    label: 'HKKMS06 $\nu_\mu$',
    dashistyle:{
         color: 1,
         linewidth: 3,
         alpha: 1.,
         filled: False,
         },
    histscatter: 'line'
    },
    {name: 'prompt_nue',
    label: 'ERS $\nu_e$',
    dashistyle:{
         color: 3,
         linewidth: 3,
         alpha: 1.,
         filled: False,
         linestyle: 'solid',
         },
    histscatter: 'line'
    },
    {name: 'prompt_numu',
    label: 'ERS $\nu_\mu$',
    dashistyle:{
         color: 3,
         linewidth: 3,
         alpha: 1.,
         filled: False,
         linestyle: 'solid',
         },
    histscatter: 'line'
    } 
] 




