# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pyevsel - HEP eventselection with python
email: achim.stoessl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Pyevsel - HEP style event selection
baseurl: "/pyevsel" # the subpath of your site, e.g. /blog
url: "http://achim1.github.io" # the base hostname & protocol for your site
twitter_username: icecubr
github_username:  achim1
include: ["_static", "_sources","_modules"]
highlighter: rouge
# Build settings
markdown: kramdown
