language: python
python:
  - 2.7
  - 3.5

notifications:
  email: false

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
# The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
#  - pip install -r requirements.txt
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pandas tables 
  - python setup.py install
  - pip install coveralls
script:
  coverage run --source=pyevsel setup.py test
after_success:
  coveralls
